### ISSUE TITLE
App Crashing after Waking from Sleep/Hibernate

### ISSUE THREAD

**Issue by ChadEstes82** [boarder2/Latest-Chatty-8#53] opened 2016-04-25 00:56 UTC
Latest Chatty 8 is crashing to desktop after waking a computer from Hibernate or Sleep.  Using the reset app function and then rebooting the computer will resolve the issue until the computer hibernates or sleeps again. 

Windows 10 pro Insider Prview
Build 14328.rs1_release.160418-1609

[LatestChatty Crash Error.zip](https://github.com/boarder2/Latest-Chatty-8/files/233774/LatestChatty.Crash.Error.zip)

**Comment by boarder2** [comment] 2016-04-25 21:21
I can't reproduce this since the only Insider machines I have are running under VirtualBox which apparently doesn't support sleeping guests.

I will add better crash analytics as part of Issue #54 which may help track this down.

Since this doesn't seem to be happening on release builds I'm not terribly worried about it.  Will keep an eye on it, though.

**Comment by boarder2** [comment] 2016-05-04 07:33
@ChadEstes82 If you can get this to happen again with the latest public version (2.11.102) I should be in a better position for logging unhandled exceptions.

Let me know if you're able to cause it again.

**Comment by boarder2** [comment] 2016-07-01 20:11
@ChadEstes82 Is this still happening for you with recent updates to the app and/or insider builds?

**Comment by ChadEstes82** [comment] 2016-07-01 21:08
Negative. App is working mostly great.

**Comment by boarder2** [comment] 2016-07-01 21:15
Awesome, closing.

**Closed as completed by boarder2** 2016-07-01 21:15 UTC
Labels: low priority
